name: Build

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    schedule:
        # 06:00 every saturday:
        - cron:  '0 6 * * 6'
    workflow_dispatch:
        inputs:
            maven-action:
                description: 'Type "release" to build a new release, all other values trigger a snapshot build'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
           - name: Checkout source
             uses: actions/checkout@v2
           - name: Set up JDK 1.8
             uses: actions/setup-java@v1
             with:
                 java-version: 1.8
                 server-id: ossrh
                 server-username: OSSRH_USER
                 server-password: OSSRH_PASSWORD
                 gpg-private-key: ${{secrets.GPG_SECRET_KEY}}
                 gpg-passphrase: GPG_SECRET_KEY_PASSPHRASE
           - name: Build snapshot using Maven
             if: github.event.inputs.maven-action != 'release'
             run: mvn --batch-mode deploy
             env:
                 OSSRH_USER: ${{secrets.OSSRH_USER}}
                 OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
                 GPG_SECRET_KEY_PASSPHRASE: ${{secrets.GPG_SECRET_KEY_PASSPHRASE}}
           - name: Build release using Maven
             if: github.event.inputs.maven-action == 'release'
             run: mvn --batch-mode release:prepare release:perform
             env:
                 OSSRH_USER: ${{secrets.OSSRH_USER}}
                 OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
                 GPG_SECRET_KEY_PASSPHRASE: ${{secrets.GPG_SECRET_KEY_PASSPHRASE}}
                 