name: Build

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    schedule:
        # 06:00 every saturday:
        - cron:  '0 6 * * 6'
          branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
           - name: Checkout source
             uses: actions/checkout@v2
           - name: Install GPG secret key
             run: |
                 echo ${{secrets.GPG_SECRET_KEY}} | gpg --batch --import
                 gpg --list-secret-keys
           - name: Set up JDK 1.8
             uses: actions/setup-java@v1
             with:
                 java-version: 1.8
           - name: Build with Maven
             run: mvn --batch-mode install
