name: Build

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    schedule:
        # 06:00 every saturday:
        - cron:  '0 6 * * 6'
          branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
           - name: Checkout source
             uses: actions/checkout@v2
           - name: Install GPG secret key
             run: echo "$GPG_SECRET_KEY" | gpg --batch --import
             env:
                 GPG_SECRET_KEY: ${{secrets.GPG_SECRET_KEY}}
           - name: Set up JDK 1.8
             uses: actions/setup-java@v1
             with:
                 java-version: 1.8
           - name: Build with Maven
             run: mvn --batch-mode -Dgpg.passphrase=$GPG_SECRET_KEY_PASSPHRASE clean install
             env:
                 GPG_SECRET_KEY_PASSPHRASE: ${{secrets.GPG_SECRET_KEY_PASSPHRASE}}
